version: "3.9"

services:
  database:
    image: mysql:8.3
    env_file: .database.env
    command: --init-file /data/application/init.sql
    volumes:
      - dev-volume:/var/lib/mysql
      - ./platform/database/init.d/init.sql:/data/application/init.sql
      - ./platform/database/conf.d/my.cnf:/db/conf.d:/etc/mysql/conf.d/my.cnf
    restart: unless-stopped
    container_name: AIM_Coding_Test-mysql
    networks:
      - dev-network
    ports:
      - "3306:3306"

  redis:
    image: redis:7.2.4-alpine
    container_name: AIM_Coding_Test-redis
    restart: unless-stopped
    networks:
      - dev-network
    ports:
      - "6379:6379"

#  web_server_dev:
#    env_file: .app.env
#    build:
#      context: .
#      dockerfile: Dockerfile
#      target: dev
#    container_name: AIM_Coding_Test-gin_dev
#    ports:
#      - "3000:3000"
#    depends_on:
#      - database
#      - redis
#    volumes:
#      - ./:/build
#    networks:
#      - dev-network

  web_server_prod:
    env_file: .app.env
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: AIM_Coding_Test-gin_prod
    volumes:
      - ./docs:/docs
    ports:
      - "3000:3000"
    depends_on:
      - database
      - redis
    networks:
      - dev-network



volumes:
  dev-volume: {}

networks:
  dev-network:
    driver: bridge
